### ISSUE TITLE
termux-app注释文档

### ISSUE THREAD

**Issue by butub1** [bingduoduo1/public_doc#1]
@Melina-Zh 
1. run一下[termux-app](git@github.com:butub1/termux-app.git)的代码，在你的电脑上能不能跑
2. 读termux-app的注释，理清楚代码的逻辑
3. 写一份关于termux-app的说明文档，整个app的实现

ddl: 周三
要求：提交文档

**Comment by Melina-Zh** [comment]
已成功编译运行termux源码
[termux关键代码逻辑](https://github.com/bingduoduo1/public_doc)
文档持续编辑中
